# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  repositoryName: '$(dockerId).azurecr.io/microsoft/ruby-on-azure'
  imageName: '$(repositoryName):$(build.buildId)'

steps:
- script: |
    docker login -u $(dockerId) -p $pswd $(dockerid).azurecr.io
    docker build -f Dockerfile --cache-from $(repositoryName):latest -t $(imageName) .
    docker run -i $(imageName) bundle exec rails test
    docker push $(imageName)
  env:
    pswd: $(dockerPassword)