version: '3'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    command: bundle exec rails s -p 3333 -b '0.0.0.0'
    volumes:
      - .:/var/app
    tmpfs: /var/app/tmp/pids
    ports:
      - 3333:3333
